#!/bin/bash
# Adrian Vollmer, SySS GmbH 2019
# This script is run as a systemd daemon. It extracts the tarball if
# necessary, then runs the python script

TARBALL=/root/lg.tar.gz
TARGET_DIR="$(dirname "$TARBALL")/lg"

if [ ! -f "$TARGET_DIR/lauschgerät.py" ] ; then
    mkdir -p "$TARGET_DIR"
    cd "$TARGET_DIR"
    tar xfz "$TARBALL"
fi

exec "$TARGET_DIR/lauschgerät.py"
